version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: Ngozi
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ngozika1105@gmail.com
      PGADMIN_DEFAULT_PASSWORD: joerald123
    ports:
      - "5050:80"
    networks:
      - my_network

networks:
  my_network:
